### ISSUE TITLE
Merge wiki updates

### ISSUE THREAD

**Issue by shunkosa** [SFDO-Community-Sprints/GrassrootsMobileSurveyApp#52]
@johncastelloe and @travelertrish proposed wonderful updates to wiki for nonprofit admins. 
https://github.com/johncastelloe/DraftGRMSWiki/wiki

Review the details of the differences together and reflect the changes in the main wiki. If you have any questions and feedbacks to the proposed changes, feel free to comment to this thread.

- [x] Home.md (Partially merged)
- [x] About.md (merged)
- [x] Architecture-Overview.md (merged)
- [x] Development-Environment-Setup.md (merged)
- [x] Heroku-Initial-Setup.md (merged)
- [x] Mobile-Environment-Setup.md (merged)
- [x] Publish-and-Build.md (merged)
- [x] Retrieve-the-Latest-Update.md (deleted)
- [x] Salesforce-Initial-Setup.md (partially merged)
- [x] Onbording-Field-Workers.md (copied) 
- [x] Localization (should we extract this page from configuration page?)

**Comment by shunkosa** [comment]
Here are some trivial comments...
* Home
  * Maybe look better if we have a section title before *Nonprofis:* ? It seems to me that the first four bullet points could logically be split into two.
* Further Customization > Mobiel App Customization
  * We switched to publish generic apk files, so now the logo image cannot be changed unless the administrator distributes the mobile application by the command. See also #34. Probably we should remove this page or move to developer section. (but keep the configuration sections such as record types, page layouts, etc)

**Comment by shunkosa** [comment]
Sorry, one more thing, can you list the pages you updated/added?

**Comment by johncastelloe** [comment]
Sure, I think this WinMerge report is more than you're asking for, but it's just so easy and fun I can't help it. Oh, and please tell me if you know of any Git tools that can do this kind of thing. I've been using WinMerge for over 20 years and feel so sluggish whenever I try to use Git instead :).

You can download [wiki-diffs.zip](https://github.com/SFDO-Community-Sprints/GrassrootsMobileSurveyApp/files/6945720/wiki-diffs.zip) to get this stuff:

| File/Folder | Description |
|---|---|
|wiki-diffs.csv|CSV diff table|
|wiki-diffs.md|Markdown diff table|
|wiki-diffs.html|Full HTML report (color-coded side-by-side file comparisons)|
|wiki-2021-07-30|"Before" snapshot|
|wiki-2021-08-05|"After" snapshot|

And here's a copy/paste of wiki-diffs.md:

|Filename                            |Newer File|Differences|Short Result|Left Size|Right Size|Left Date              |Right Date             |
|------------------------------------|----------|-----------|------------|---------|----------|-----------------------|-----------------------|
|_Sidebar.md                         |->        |4          |Different   |825      |1,266     |  7/31/2021 6:36:06 AM |* 8/5/2021 6:41:51 PM  |
|About.md                            |->        |9          |Different   |2,324    |2,411     |  7/30/2021 5:12:34 PM |* 8/3/2021 11:10:25 AM |
|Architecture-Overview.md            |->        |5          |Different   |1,377    |1,369     |  6/29/2021 5:45:41 PM |* 8/5/2021 1:18:24 PM  |
|Development-Environment-Setup.md    |->        |6          |Different   |1,444    |1,600     |  6/29/2021 5:45:41 PM |* 8/5/2021 6:27:18 PM  |
|Heroku-Initial-Setup.md             |->        |14         |Different   |2,617    |4,706     |  6/29/2021 5:45:41 PM |* 8/5/2021 4:20:43 PM  |
|Home.md                             |->        |6          |Different   |1,207    |2,262     |  7/30/2021 11:26:32 AM|* 8/4/2021 6:07:25 PM  |
|Mobile-Environment-Setup.md         |->        |6          |Different   |1,426    |1,382     |  7/28/2021 9:19:03 PM |* 8/5/2021 4:38:14 PM  |
|Publish-and-Build.md                |->        |4          |Different   |792      |805       |  7/28/2021 9:19:03 PM |* 8/5/2021 6:38:01 PM  |
|Retrieve-the-Latest-Update.md       |->        |2          |Different   |502      |427       |  6/29/2021 5:45:41 PM |* 8/4/2021 6:32:04 PM  |
|Salesforce-Initial-Setup.md         |->        |19         |Different   |4,203    |8,214     |  7/28/2021 9:19:03 PM |* 8/5/2021 2:56:02 PM  |
|Survey-Record-Types.md              |->        |1          |Different   |2,656    |2,602     |  7/30/2021 11:26:32 AM|* 7/31/2021 7:19:49 AM |
|2021-June-Community-Sprint-(EMEA).md|-->       |*          |Right Only  |         |3,741     |                       |* 7/31/2021 7:26:20 AM |
|Localization.md                     |-->       |*          |Right Only  |         |624       |                       |* 8/4/2021 6:11:46 PM  |
|Mobile-App-Customization.md         |-->       |*          |Right Only  |         |269       |                       |* 8/4/2021 6:08:37 PM  |
|Onboarding-Field-Workers.md         |-->       |*          |Right Only  |         |1,548     |                       |* 8/5/2021 6:13:06 PM  |
|Privacy-Policy.md                   |-->       |*          |Right Only  |         |4,624     |                       |* 8/2/2021 11:52:51 AM |
|Setting-Up-Automation.md            |-->       |*          |Right Only  |         |133       |                       |* 8/5/2021 6:17:16 PM  |
|Configuration.md                    |<--       |*          |Left Only   |2,713    |          |* 6/29/2021 5:45:41 PM |                       |
|2021-February-Community-Sprint.md   |==        |0          |Identical   |2,228    |2,228     |  6/29/2021 5:45:41 PM |  6/29/2021 5:45:41 PM |
|2021-June-Community-Sprint.md       |==        |0          |Identical   |4,188    |4,188     |  6/29/2021 5:45:41 PM |  6/29/2021 5:45:41 PM |
|Contribution-Guideline.md           |==        |0          |Identical   |1,287    |1,287     |  7/30/2021 11:26:32 AM|  7/30/2021 11:26:32 AM|
|Data-Model.md                       |==        |0          |Identical   |765      |765       |  6/29/2021 5:45:41 PM |  6/29/2021 5:45:41 PM |
|Release.md                          |==        |0          |Identical   |212      |212       |  7/28/2021 9:19:03 PM |  7/28/2021 9:19:03 PM |

**Comment by shunkosa** [comment]
Thank you again!! I'm merging the small diffs. But I'm also looking forward to getting the feedback from the other core members :)

**Comment by shunkosa** [comment]
Almost there! I also updated the sidebar. IMO it may be enough just showing configuration related pages.

**Comment by kdveverka** [comment]
@shunkosa - We'd like to go ahead and finish the merges here on what John & Trish had since this one is kinda stuck waiting for other reviewers. Would that be okay?

**Comment by johncastelloe** [comment]
I've finished merging in the updates from the work I did with Trish back in July/August, and here's a summary of all the changes. Feel free to mark "Closed" if there are no concerns.

1. Lots of major content-related changes to the Salesforce-Initial-Setup page. There's nothing new since the August version, and I think we were just waiting for more feedback before merging (but we never did get any feedback). More changes will be needed to catch up with development progress since August, but I can't think of anything urgent. Because we might be changing the Record Types soon, I think it makes sense to wait until most decisions have been made before doing major revisions again.
2. A few minor content-related changes to the Home page, most notably the two extra paragraphs near the top under "Architecture Overview."
3. Spelling correction from "Onbording" to "Onboarding" for the Onboarding-Field-Workers page. This renaming caused a loss of page edit history, but I didn't change any content from last time, and it was all new content then anyway.
4. Very minor changes to About and Contribution-Guideline pages.
5. Update of the Sidebar to add recent meeting links correct a few typos.

**Comment by shunkosa** [comment]
Thanks @johncastelloe, I just reverted the link of mobile app customization page to record type and layouts page because the page doesn't exist. But the others looks very good! Thank you again!

**Comment by johncastelloe** [comment]
@shunkosa, I intentionally removed the link to the Record Type and Layouts page because all of the content there was already moved to the Salesforce Initial Setup page. The "Further Customization" section is intended to be only for customizations that are beyond the basic setup tasks, like "now that you've finished setting things up, how can you make it work even better for your nonprofit?" I believe @travelertrish is envisioning the Setting Up Automation in Salesforce page to become a demonstration of how you could write Flows to get all the data moved from the Field Survey object into other objects like Contacts, Opportunities, and whatever Custom Objects they already use to do their program management. For a typical nonprofit it wouldn't be productive to just let all the survey data sit there in the Field Survey record, right? It's really meant to be copied over to whatever Objects are most meaningful in their existing data model.

**Comment by johncastelloe** [comment]
@kdveverka, maybe we could go ahead and create a new task for writing content for the "Setting Up Automation in Salesforce" page. It could be a fun project for someone who is already familiar with Flows or wants to learn them better. We could choose one of our user stories and show how to [make it so](https://www.youtube.com/watch?v=FaLyasJPyUU). That is, assuming I'm fairly representing your & @travelertrish's & @shunkosa's and others' vision for our Wiki. Feel free to assign me to the task for now, although of course it's really Trish's brainchild. I can talk with her about it in a few days when we're already planning to chat about other things.

**Comment by shunkosa** [comment]
Definitely agree with the automation and the actual objects!

**Comment by kdveverka** [comment]
@johncastelloe - adding this task. I missed the tag to me in the larger convo- sorry about that!
